listen_port: 5433
master:
    host: localhost
    port: 5432
configurations:
    - slave1:
        match:
            application_name: slave1
        filter:
            include_databases: [postgres]
            # exclude_databases: []
            # include_tablespaces: []
            exclude_tablespaces: [spc_slave1]
    - slave2:
        match:
            application_name: slave2
        filter:
            include_tablespaces: [spc_slave2]
